services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:${DEBEZIUM_VERSION:-1.4}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    container_name: kafka
    image: debezium/kafka:${DEBEZIUM_VERSION:-1.4}
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  mysql:
    container_name: mysql
    image: mysql:${MYSQL_VERSION:-8.0.26}
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - C:/Users/Sahar/Desktop/ecommorce-project/docker/mysql/mysql.cnf:/etc/mysql/my.cnf
        - ./docker/mysql/data.sql:/docker-entrypoint-initdb.d/00-data.sql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.3.0}
    ports:
      - 9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  connect:
    container_name: connect
    image: debezium/connect:2.5
    build:
      context: docker/connect
    ports:
      - 8083:8083
      - 5005:5005
    depends_on:
      - kafka
      - mysql
      - elastic
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-7.3.0}
    ports:
      - 5601:5601
    depends_on:
      - elastic
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200

  control-center:
    container_name: control-center
    image: confluentinc/cp-enterprise-control-center:6.2.0
    depends_on:
      - connect
    ports:
      - 9021:9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
